FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
COPY cmd ./cmd
COPY db ./db
COPY internal ./internal
RUN go test ./...
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/woms-api ./cmd/api

FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /
COPY --from=build /out/woms-api /woms-api
COPY --from=build /src/db /db
EXPOSE 8080
ENTRYPOINT ["/woms-api"]
