FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod ./
COPY cmd ./cmd
COPY internal ./internal
RUN go test ./...
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/woms-scheduler-worker ./cmd/scheduler-worker

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/woms-scheduler-worker /woms-scheduler-worker
ENTRYPOINT ["/woms-scheduler-worker"]
