global:
  imagePullPolicy: IfNotPresent

imageRegistry: docker.io/d11nn

api:
  replicaCount: 2
  pdb:
    minAvailable: 1
  image:
    repository: woms-api
    tag: v0.1.21
  jwtSecret: ""
  env:
    store: postgres
    demoSeedData: "true"
    databaseUrl: postgres://woms:woms@postgres:5432/woms?sslmode=disable
    redisAddr: redis-master:6379
    kafkaBrokers: kafka:9092
    scheduleTopic: woms.schedule.jobs
    kafkaPublishEnabled: "true"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

worker:
  replicaCount: 1
  image:
    repository: woms-scheduler-worker
    tag: v0.1.21
  env:
    databaseUrl: postgres://woms:woms@postgres:5432/woms?sslmode=disable
    minJobDurationMs: "0"
    maxRetries: "3"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 512Mi

web:
  replicaCount: 2
  pdb:
    minAvailable: 1
  image:
    repository: woms-web
    tag: v0.1.21
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

ingress:
  enabled: false
  className: nginx
  host: woms.local
  tls:
    enabled: false
    secretName: woms-tls
  auth:
    enabled: true

keda:
  enabled: true
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 30
  cooldownPeriod: 120
  hpa:
    scaleUp:
      stabilizationWindowSeconds: 0
      percent: 100
      periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 120
      percent: 50
      periodSeconds: 60
  kafka:
    enabled: true
    bootstrapServers: kafka:9092
    topic: woms.schedule.jobs
    consumerGroup: woms-scheduler-workers
    lagThreshold: "10"
    offsetResetPolicy: latest
  cpu:
    enabled: true
    targetUtilization: "70"

postgresql:
  enabled: true
  fullnameOverride: postgres
  auth:
    username: woms
    password: woms
    database: woms
  primary:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

redis:
  enabled: true
  fullnameOverride: redis
  architecture: standalone
  auth:
    enabled: false
  master:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi

kafka:
  enabled: true
  fullnameOverride: kafka
  controller:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  broker:
    replicaCount: 0
  kraft:
    enabled: true
  listeners:
    client:
      protocol: PLAINTEXT
  provisioning:
    enabled: false

kafkaTopic:
  enabled: true
  image:
    repository: docker.io/bitnami/kafka
    tag: 3.7.0-debian-12-r6
    pullPolicy: IfNotPresent
  activeDeadlineSeconds: 420
  wait:
    maxAttempts: 60
    sleepSeconds: 5
  partitions: 0
  replicationFactor: 1
