apiVersion: v1
kind: Secret
metadata:
  name: {{ include "woms.fullname" . }}-api
  labels:
    {{- include "woms.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.api.jwtSecret | quote }}
